sudo: required
services:
  - docker

before_install:
  - docker build -t akalpita123/react-multitest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akalpita123/react-multitest npm test -- --coverage

after_success:
  - docker build -t akalpita123/multi-client  ./client
  - docker build -t akalpita123/multi-nginx  ./nginx 
  - docker build -t akalpita123/multi-server  ./server 
  - docker build -t akalpita123/multi-worker  ./worker
  #login in to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #push all to docker hub
  - docker push akalpita123/multi-client
  - docker push akalpita123/multi-nginx
  - docker push akalpita123/multi-server
  - docker push akalpita123/multi-worker
